<?php

namespace ContainerJjpxGLs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServicioInvitacionUsuariosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ServicioInvitacionUsuarios' shared autowired service.
     *
     * @return \App\Service\ServicioInvitacionUsuarios
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ServicioInvitacionUsuarios.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\ServicioInvitacionUsuarios'])) {
            return $container->privates['App\\Service\\ServicioInvitacionUsuarios'];
        }

        return $container->privates['App\\Service\\ServicioInvitacionUsuarios'] = new \App\Service\ServicioInvitacionUsuarios(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['App\\Repository\\EventosRepository'] ?? $container->load('getEventosRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), $a, ($container->privates['App\\Repository\\ParticipacionRepository'] ?? $container->load('getParticipacionRepositoryService')));
    }
}
