<?php

namespace ContainerIpbcDjE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1y1Lq0jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1y1Lq0j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1y1Lq0j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'juegosRepository' => ['privates', 'App\\Repository\\JuegosRepository', 'getJuegosRepositoryService', true],
        ], [
            'juegosRepository' => 'App\\Repository\\JuegosRepository',
        ]);
    }
}
