<?php

namespace ContainerQLliKgV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O2PJA6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o2_PJA6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o2_PJA6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'juego' => ['privates', '.errored..service_locator.o2_PJA6.App\\Entity\\Juegos', NULL, 'Cannot autowire service ".service_locator.o2_PJA6": it needs an instance of "App\\Entity\\Juegos" but this type has been excluded in "config/services.yaml".'],
        ], [
            'juego' => 'App\\Entity\\Juegos',
        ]);
    }
}
