<?php

namespace ContainerRtB9b2r;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IxNz1ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ix_Nz1Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ix_Nz1Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'mesasRepository' => ['privates', 'App\\Repository\\MesasRepository', 'getMesasRepositoryService', true],
        ], [
            'doctrine' => '?',
            'mesasRepository' => 'App\\Repository\\MesasRepository',
        ]);
    }
}
