<?php

namespace ContainerRtB9b2r;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPass_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ResetPass.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\ResetPass.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:reset-pass', [0 => 'app:modify-user'], 'Reseteo de password.', false, #[\Closure(name: 'App\\Command\\ResetPass')] function () use ($container): \App\Command\ResetPass {
            return ($container->privates['App\\Command\\ResetPass'] ?? $container->load('getResetPassService'));
        });
    }
}
