<?php

namespace ContainerRtB9b2r;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPassService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ResetPass' shared autowired service.
     *
     * @return \App\Command\ResetPass
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ResetPass.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ServicioPersonalUser.php';

        $container->privates['App\\Command\\ResetPass'] = $instance = new \App\Command\ResetPass(new \App\Service\ServicioPersonalUser(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService'))));

        $instance->setName('app:reset-pass');
        $instance->setAliases([0 => 'app:modify-user']);
        $instance->setDescription('Reseteo de password.');

        return $instance;
    }
}
