<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQLliKgV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQLliKgV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQLliKgV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQLliKgV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQLliKgV\App_KernelDevDebugContainer([
    'container.build_hash' => 'QLliKgV',
    'container.build_id' => 'dde1a4c1',
    'container.build_time' => 1677973877,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQLliKgV');
