<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEMxNJ4C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEMxNJ4C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEMxNJ4C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEMxNJ4C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEMxNJ4C\App_KernelDevDebugContainer([
    'container.build_hash' => 'EMxNJ4C',
    'container.build_id' => '81f21ae5',
    'container.build_time' => 1678223742,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEMxNJ4C');
