<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX3N0hu9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX3N0hu9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX3N0hu9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX3N0hu9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX3N0hu9\App_KernelDevDebugContainer([
    'container.build_hash' => 'X3N0hu9',
    'container.build_id' => '3900bc5e',
    'container.build_time' => 1677068549,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX3N0hu9');
