<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\Inicio::login'], [], [['text', '/']], [], [], []],
    'app_inicio_inicio' => [[], ['_controller' => 'App\\Controller\\Inicio::inicio'], [], [['text', '/index']], [], [], []],
    'app_juegos_index' => [[], ['_controller' => 'App\\Controller\\JuegosController::index'], [], [['text', '/juegos/']], [], [], []],
    'app_juegos_new' => [[], ['_controller' => 'App\\Controller\\JuegosController::new'], [], [['text', '/juegos/nuevo']], [], [], []],
    'app_juegos_show' => [['id'], ['_controller' => 'App\\Controller\\JuegosController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/juegos']], [], [], []],
    'app_juegos_edit' => [['id'], ['_controller' => 'App\\Controller\\JuegosController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/juegos']], [], [], []],
    'app_juegos_delete' => [['id'], ['_controller' => 'App\\Controller\\JuegosController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/juegos']], [], [], []],
    'app_juegos_mostrarreservas' => [['altura', 'anchura'], ['_controller' => 'App\\Controller\\JuegosController::mostrarReservas'], [], [['variable', '/', '[^/]++', 'anchura', true], ['variable', '/', '[^/]++', 'altura', true], ['text', '/juegos/mostrarJuegos']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginUserController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginUserController::logout'], [], [['text', '/logout']], [], [], []],
    'app_mesas' => [[], ['_controller' => 'App\\Controller\\MesasController::index'], [], [['text', '/mesas']], [], [], []],
    'app_mesas_createmesas' => [[], ['_controller' => 'App\\Controller\\MesasController::createMesas'], [], [['text', '/nuevamesa']], [], [], []],
    'app_mesas_mostarmesas' => [['fecha'], ['_controller' => 'App\\Controller\\MesasController::mostarMesas'], [], [['variable', '/', '[^/]++', 'fecha', true], ['text', '/mostrarmesas']], [], [], []],
    'app_mesas_modificarmesa' => [[], ['_controller' => 'App\\Controller\\MesasController::ModificarMesa'], [], [['text', '/editarmemsa']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_reservas' => [[], ['_controller' => 'App\\Controller\\ReservasController::index'], [], [['text', '/reservas']], [], [], []],
    'app_reservas_mostrarreservas' => [['fecha', 'hora'], ['_controller' => 'App\\Controller\\ReservasController::mostrarReservas'], [], [['variable', '/', '[^/]++', 'hora', true], ['variable', '/', '[^/]++', 'fecha', true], ['text', '/mostrarreservas']], [], [], []],
    'app_reservas_createreservas' => [[], ['_controller' => 'App\\Controller\\ReservasController::createReservas'], [], [['text', '/nuevaReserva']], [], [], []],
    'app_misreservas' => [['id'], ['_controller' => 'App\\Controller\\ReservasController::mostrarReservasP'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/reservasPersonales']], [], [], []],
];
