<?php

namespace Container4ISreoT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CBoodCpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CBoodCp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CBoodCp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'App\\Controller\\JuegosController::delete' => ['privates', '.service_locator.Cod3346', 'get_ServiceLocator_Cod3346Service', true],
            'App\\Controller\\JuegosController::edit' => ['privates', '.service_locator.Cod3346', 'get_ServiceLocator_Cod3346Service', true],
            'App\\Controller\\JuegosController::index' => ['privates', '.service_locator.1y1Lq0j', 'get_ServiceLocator_1y1Lq0jService', true],
            'App\\Controller\\JuegosController::new' => ['privates', '.service_locator.1y1Lq0j', 'get_ServiceLocator_1y1Lq0jService', true],
            'App\\Controller\\JuegosController::show' => ['privates', '.service_locator.o2_PJA6', 'get_ServiceLocator_O2PJA6Service', true],
            'App\\Controller\\LoginUserController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.xVV8u.q', 'get_ServiceLocator_XVV8u_QService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'App\\Controller\\JuegosController:delete' => ['privates', '.service_locator.Cod3346', 'get_ServiceLocator_Cod3346Service', true],
            'App\\Controller\\JuegosController:edit' => ['privates', '.service_locator.Cod3346', 'get_ServiceLocator_Cod3346Service', true],
            'App\\Controller\\JuegosController:index' => ['privates', '.service_locator.1y1Lq0j', 'get_ServiceLocator_1y1Lq0jService', true],
            'App\\Controller\\JuegosController:new' => ['privates', '.service_locator.1y1Lq0j', 'get_ServiceLocator_1y1Lq0jService', true],
            'App\\Controller\\JuegosController:show' => ['privates', '.service_locator.o2_PJA6', 'get_ServiceLocator_O2PJA6Service', true],
            'App\\Controller\\LoginUserController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.xVV8u.q', 'get_ServiceLocator_XVV8u_QService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => '?',
            'App\\Controller\\JuegosController::delete' => '?',
            'App\\Controller\\JuegosController::edit' => '?',
            'App\\Controller\\JuegosController::index' => '?',
            'App\\Controller\\JuegosController::new' => '?',
            'App\\Controller\\JuegosController::show' => '?',
            'App\\Controller\\LoginUserController::login' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => '?',
            'App\\Controller\\JuegosController:delete' => '?',
            'App\\Controller\\JuegosController:edit' => '?',
            'App\\Controller\\JuegosController:index' => '?',
            'App\\Controller\\JuegosController:new' => '?',
            'App\\Controller\\JuegosController:show' => '?',
            'App\\Controller\\LoginUserController:login' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
