<?php

namespace ContainerUFnMYXk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cod3346Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cod3346' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cod3346'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'juego' => ['privates', '.errored..service_locator.Cod3346.App\\Entity\\Juegos', NULL, 'Cannot autowire service ".service_locator.Cod3346": it needs an instance of "App\\Entity\\Juegos" but this type has been excluded in "config/services.yaml".'],
            'juegosRepository' => ['privates', 'App\\Repository\\JuegosRepository', 'getJuegosRepositoryService', true],
        ], [
            'juego' => 'App\\Entity\\Juegos',
            'juegosRepository' => 'App\\Repository\\JuegosRepository',
        ]);
    }
}
