<?php

namespace ContainerUFnMYXk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJuegos2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.o2_PJA6.App\Entity\Juegos' shared service.
     *
     * @return \App\Entity\Juegos
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.o2_PJA6": it needs an instance of "App\\Entity\\Juegos" but this type has been excluded in "config/services.yaml".');
    }
}
